variables:
    VPC_NAME:
        required: true
        description: What is the name of the VPC?
        default: test-vpc
    VPC_OCTETS:
        required: true
        description: the /16 net of the VPC to look for
        default: 10.8.0.0
    REGION:
        required: true
        description: use default except for multiple region use cases
        default: "PLAN::region"
        type: string
    PUBLIC_ROUTE_NAME:
        required: true
        description: the name to give to the public route
        default: test-public-route
    PUBLIC_SUBNET_NAME:
        required: true
        description: the cloudcoreo name of the public vpc subnets
        default: test-public-subnet
    PRIVATE_ROUTE_NAME:
        required: true
        description: the name to give to the private route
        default: test-private-route
    PRIVATE_SUBNET_NAME:
        required: true
        description: the cloudcoreo name of the private vpc subnets
        default: test-private-subnet
    SUFFIX:
        required: false
        description: when used will use the value to suffix the names of all converged objects
        type: string
    VPC_TAGS:
        required: false
        description: tags to apply to the vpc
        type: array
        default:
            - 
    SUBNET_NUM_ZONES:
        required: true
        description: How many private and public subnets should be created
        type: number
        default: 2
    PRIVATE_ROUTE_NUM_TABLES
        required: true
        description: How many private route tables to create
        type: number
        default: 2
